config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  post '/' => 'welcome#parse', as: 'parse'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def parse
    logger = Logger.new("#{Rails.root}/log/interia.log")
    job_parser = Services::JobParser.new(logger)
    @result = job_parser.call(params[:job_structure])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Interia
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/welcome/_form.html.haml
= form_tag parse_url, html: { class: 'col-xs-12' } do
  %fieldset.form-group
    = text_area_tag 'job_structure', nil, class: 'form-control'
  = submit_tag 'Parsuj', class: 'btn btn-primary'

app/views/welcome/index.html.haml
.row
  %h1 Lista zadań
  = render partial: 'form'

app/views/welcome/parse.html.haml
.row
  %h1 Lista zadań
  = render partial: 'form'

.row.top-buffer
  %h1 Wynik
  = @result